using System.Collections;
using System.Collections.Generic;
using Unity.FPS.Game;
using UnityEngine;

namespace Unity.FPS.Gameplay
{
    /// <summary>
    /// 충전용 발사체를 발사할때 충전량에 따른 발사체의 속성값을 설정 
    /// </summary>
    public class ProjectileChargeParametor : MonoBehaviour
    {
        #region Variables
        private ProjectileBase projectileBase;

        public MinMaxFloat Damage;
        public MinMaxFloat Speed;
        public MinMaxFloat GravityDown;
        public MinMaxFloat Raidus;
        #endregion

        private void OnEnable()
        {
            //참조
            projectileBase = GetComponent<ProjectileBase>();
            projectileBase.OnShoot += OnShoot;
        }

        //발사체 발사시 projectileBase의 onShoot 델리게이트 함수에서 호출
        //발사의 속성값을 Charge 값에 따라 설정
        void OnShoot()
        {
            //충전량에 따라 발사체 속성값을 설정 
            ProjectileStandard projectileStandard = GetComponent<ProjectileStandard>();
            projectileStandard.damage = Damage.GetValueFromRatio(projectileBase.InitialCharge);
            projectileStandard.speed = Speed.GetValueFromRatio(projectileBase.InitialCharge);
            projectileStandard.gravity = GravityDown.GetValueFromRatio(projectileBase.InitialCharge);
            projectileStandard.radius = Raidus.GetValueFromRatio(projectileBase.InitialCharge);
        }
    }

}

